#
# Docker NodeJS Typescript Starter
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3.6"

services:
  # Web App #
  web:
    image: web:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: yarn watch-ts
  
  # DB
  postgres:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"