#
# Docker NodeJS Typescript Starter
# Example Docker Compose file
#

# For more information about the directives defined here:
# https://docs.docker.com/compose/compose-file/

# Docker compose file version
version: "3"
services:
  # Web App #
  web:
    build: .
    entrypoint: yarn dev
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    env_file:
      - .env

  # DB
  postgres:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
